name       : kidletime
version    : 5.68.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kidletime-5.68.0.tar.xz : cd6309d403ea36553abc99af4fa7e4ed3f8b3b2c55d14887ef09d68e5627b3e7
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
