name       : kidletime
version    : 5.61.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kidletime-5.61.0.tar.xz : 8fb302dcc5b891ac2f06b5278bd6e08043772f3325bc209175c945280621fca2
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
