name       : kidletime
version    : 5.60.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kidletime-5.60.0.tar.xz : e7c4ca5ca3e847c37add4c81b3d430f4c4bf0214433a234a32d766c9199adb27
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
