name       : kidletime
version    : 5.76.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kidletime-5.76.0.tar.xz : 0866fc98b5b045158742f03f5810909b24f1edf374a6014d476d67fe0466eb62
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - MIT
component  : programming.library
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
