name       : kidletime
version    : 5.38.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.38/kidletime-5.38.0.tar.xz : 5bd30a316ea72a44ed4e4f7f11533e5aa74fc817f360f471b2658ac560e221c5
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
