name       : kidletime
version    : 5.74.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kidletime-5.74.0.tar.xz : 62ba9e38467e74e928191200109e9312f1f6959a6b9474bf1a47c95833ae7feb
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
