name       : kidletime
version    : 5.50.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kidletime-5.50.0.tar.xz : 215ab778dad24cdc6ba946425ddcc7bc82af79de241bae031447c7cda9860fcf
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
