name       : kidletime
version    : 5.55.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kidletime-5.55.0.tar.xz : 2f34d71383ed038318a21dddab7de71a8d67f80df430dba174ee43c90cfc06cf
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
