name       : kidletime
version    : 5.43.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kidletime-5.43.0.tar.xz : 72edf2d3907eea4367aa5f84ebaee843a9bf69f9defd1bb603dc3af757cba2ca
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
