name       : kidletime
version    : 5.106.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kidletime-5.106.0.tar.xz : a4df680c51a1c86daaa989241b30a3c4f6ce34440e7539766cd61376fe4736f5
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - MIT
component  : programming.library
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
optimize   : lto
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
