name       : kidletime
version    : 5.62.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kidletime-5.62.0.tar.xz : dd2b6a9f7815c8e84b635e694cbf9ee207996d2cf3adb5a85eadd4a8de37f276
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
